logging:
  level:
    com.example.kotlinserializationjson: DEBUG
    org.springframework.boot.web.embedded.netty.NettyWebServer: INFO
    root: WARN
  file.name: logs/application.log
  pattern.level: "%5p [${info.app.name},%X{traceId:-},%X{spanId:-}]"
